### ISSUE TITLE
EntityIdResolver fails on entities when the id is not called id

### ISSUE THREAD

**Issue by iltar** [iltar/http-bundle#12]
The EntityIdResolver currently only supports the `getId` functionality because it makes the assumption that every entity calls the property `id` and therefore the method `getId`. Via the Doctrine metadata you can find out which field is the actual id and it can be accessed using the property accessor of symfony.

http://stackoverflow.com/questions/6128914/how-to-get-doctrine2-entity-identifier-without-knowing-its-name

Combined primary keys is a different story and I don't think this can be supported as easily.

**Comment by xabbuh** [comment]
You may want to take a look at the [IdReader](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bridge/Doctrine/Form/ChoiceList/IdReader.php) class from the Symfony Doctrine bridge for some inspiration.

**Comment by WouterJ** [comment]
Can't this bundle simple use this IdReader class?

**Comment by iltar** [comment]
That's a good idea, I wonder why it's in the Form namespace though

**Comment by WouterJ** [comment]
It's designed completely for the ChoiceLoader of the Form component. Maybe we can make it more standalone before using it?

E.g., it uses the RuntimeException from the Form component and triggers messages which mentions the choice field type.

**Comment by iltar** [comment]
@WouterJ @xabbuh should be fixed #17, your reviewing skills are more than welcome!
